#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 600
#define WINDOW_HEIGHT 800

#define COUNT 40

#define SCALE (1.0 / COUNT)
#define SIZE (int)(WINDOW_WIDTH * SCALE)
#define LEFT_COLUMN_BOUND 0
#define RIGHT_COLUMN_BOUND (WINDOW_WIDTH - SIZE)
#define TOP_ROW_BOUND 0
#define BOTTOM_ROW_BOUND (WINDOW_HEIGHT - SIZE)

#endif
